// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "user login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.AuthLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.AuthLoginResp"
                        }
                    }
                }
            }
        },
        "/auth/logout/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "user logout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "summary": "基础接口 - 用户登出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/auth/register/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.CreateUserReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "authentication",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/auth/verifycode/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get verifycode",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "summary": "基础接口 - 获取验证码",
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.AuthVerifyCodeResp"
                        }
                    }
                }
            }
        },
        "/v1/course/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "course list",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "课程列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "班级",
                        "name": "class",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "创建时间",
                        "name": "create_tm",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "年级",
                        "name": "grade",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "根据创建时间排序 \"create_tm\" \"-create_tm\"",
                        "name": "ordering_create_tm",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "根据年级排序 \"grade\" \"-grade",
                        "name": "ordering_grade",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "根据班级总人数排序 \"total_member\" \"-total_member\"",
                        "name": "ordering_total_member",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页数,用于分页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，用于分页",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "根据课程名搜索",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.CourseListResp"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create course",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "新建课程",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.CreateCourseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "delete course",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "删除课程",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.DeleteCourseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/v1/course/class": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get class list",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "获取班级列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "年级",
                        "name": "grade",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/v1/course/enter": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "enter course",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "学生加入课程",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.EnterCourseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/v1/course/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "course info",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "根据班级获取课程信息",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.CourseInfoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.CourseInfoResp"
                        }
                    }
                }
            }
        },
        "/v1/course/update/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "update course info",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "编辑课程信息",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.UpdateCourseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/v1/exercises/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get exercises",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "获取课后练习",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "内容id",
                        "name": "content_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.GetExercisesResp"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create exercises",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "创建课后练习",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.CreateExercisesReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/v1/exercises/do/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "exercises",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "完成课后练习",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.ExercisesReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.ExercisesResp"
                        }
                    }
                }
            }
        },
        "/v1/learning_content/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "learning list",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning"
                ],
                "summary": "学习内容列表",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.LearningContentListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.LearningContentListResp"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "delete course",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning"
                ],
                "summary": "新增学习内容",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.CreateLearningContentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/v1/learning_content/learning/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "learning",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning"
                ],
                "summary": "进入学习",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "学习内容id",
                        "name": "content_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/v1/learning_content/result/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get learning result",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning"
                ],
                "summary": "查看学习情况",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.LearningResultReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.LearningResultResp"
                        }
                    }
                }
            }
        },
        "/v1/notice/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "notice",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notice"
                ],
                "summary": "通知",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.NoticeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.NoticeResp"
                        }
                    }
                }
            }
        },
        "/v1/register/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create register",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "register"
                ],
                "summary": "创建签到任务",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.CreateRegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/v1/register/do": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "register",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "register"
                ],
                "summary": "学生参与签到",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/v1/register/result/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "register result",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "register"
                ],
                "summary": "签到结果",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.RegisterResultReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.RegisterResultResp"
                        }
                    }
                }
            }
        },
        "/v1/talk/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get talk info",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "talk"
                ],
                "summary": "获取讨论话题详情",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.TalkInfoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.TalkInfoResp"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create talk",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "talk"
                ],
                "summary": "创建讨论话题",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.CreateTalkReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/v1/talk/do/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "join talk",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "talk"
                ],
                "summary": "参与讨论",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.TalkReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/v1/user/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get user info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.UserInfoResp"
                        }
                    }
                }
            }
        },
        "/v1/user/change_password/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "change user password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "修改账户密码",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.ChangePasswordReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "authorization",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.StatusResp"
                        }
                    }
                }
            }
        },
        "/v1/user/password/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get user password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "忘记密码",
                "parameters": [
                    {
                        "description": "request data",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/form_req.UserPasswordReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "authentication",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response data",
                        "schema": {
                            "$ref": "#/definitions/form_resp.UserPasswordResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "form_req.AuthLoginReq": {
            "type": "object",
            "required": [
                "captid",
                "password",
                "user_id",
                "vcode"
            ],
            "properties": {
                "captid": {
                    "description": "验证码唯一ID",
                    "type": "string"
                },
                "password": {
                    "description": "用户密码",
                    "type": "string"
                },
                "user_id": {
                    "description": "学号/工号",
                    "type": "string"
                },
                "vcode": {
                    "description": "验证码",
                    "type": "string"
                }
            }
        },
        "form_req.ChangePasswordReq": {
            "type": "object",
            "required": [
                "new_password",
                "password"
            ],
            "properties": {
                "new_password": {
                    "description": "新账户密码",
                    "type": "string"
                },
                "password": {
                    "description": "旧账户密码",
                    "type": "string"
                }
            }
        },
        "form_req.CourseInfoReq": {
            "type": "object",
            "required": [
                "class",
                "grade"
            ],
            "properties": {
                "class": {
                    "description": "班级",
                    "type": "integer"
                },
                "grade": {
                    "description": "年级",
                    "type": "integer"
                },
                "search": {
                    "description": "根据课程名称搜索",
                    "type": "string"
                }
            }
        },
        "form_req.CreateCourseReq": {
            "type": "object",
            "required": [
                "class",
                "course_name",
                "grade"
            ],
            "properties": {
                "class": {
                    "description": "班级",
                    "type": "integer"
                },
                "course_name": {
                    "description": "课程名称",
                    "type": "string"
                },
                "grade": {
                    "description": "年级",
                    "type": "integer"
                }
            }
        },
        "form_req.CreateExercisesReq": {
            "type": "object",
            "required": [
                "exercises",
                "learning_content_id"
            ],
            "properties": {
                "exercises": {
                    "description": "练习题",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/form_req.ExercisesItem"
                    }
                },
                "learning_content_id": {
                    "description": "学习内容id",
                    "type": "integer"
                }
            }
        },
        "form_req.CreateLearningContentReq": {
            "type": "object",
            "required": [
                "course_id"
            ],
            "properties": {
                "course_id": {
                    "description": "课程id",
                    "type": "integer"
                },
                "title": {
                    "description": "课程标题",
                    "type": "string"
                }
            }
        },
        "form_req.CreateRegisterReq": {
            "type": "object",
            "required": [
                "content_id",
                "register_tm"
            ],
            "properties": {
                "content_id": {
                    "description": "学习内容id",
                    "type": "integer"
                },
                "register_tm": {
                    "description": "签到时间限制，默认为2分钟",
                    "type": "integer"
                }
            }
        },
        "form_req.CreateTalkReq": {
            "type": "object",
            "properties": {
                "content_id": {
                    "description": "学习内容id",
                    "type": "integer"
                },
                "talk": {
                    "description": "讨论主题",
                    "type": "string"
                }
            }
        },
        "form_req.CreateUserReq": {
            "type": "object",
            "required": [
                "confirm",
                "password",
                "role",
                "user_id",
                "username"
            ],
            "properties": {
                "class": {
                    "description": "班级",
                    "type": "integer"
                },
                "confirm": {
                    "description": "确认用户密码",
                    "type": "string"
                },
                "grade": {
                    "description": "年级 1-6",
                    "type": "integer"
                },
                "password": {
                    "description": "用户密码",
                    "type": "string"
                },
                "role": {
                    "description": "用户角色 1-老师、2-学生",
                    "type": "integer"
                },
                "user_id": {
                    "description": "学生学号/教师工号",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "form_req.DeleteCourseReq": {
            "type": "object",
            "required": [
                "course_id"
            ],
            "properties": {
                "course_id": {
                    "description": "课程id",
                    "type": "integer"
                }
            }
        },
        "form_req.EnterCourseReq": {
            "type": "object",
            "required": [
                "course_id"
            ],
            "properties": {
                "course_id": {
                    "description": "课程id",
                    "type": "integer"
                }
            }
        },
        "form_req.ExercisesAnswer": {
            "type": "object",
            "required": [
                "answer",
                "id"
            ],
            "properties": {
                "answer": {
                    "description": "答案",
                    "type": "string"
                },
                "id": {
                    "description": "习题id",
                    "type": "integer"
                }
            }
        },
        "form_req.ExercisesItem": {
            "type": "object",
            "required": [
                "answer",
                "question",
                "type"
            ],
            "properties": {
                "answer": {
                    "description": "答案",
                    "type": "string"
                },
                "options": {
                    "description": "选项",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "question": {
                    "description": "题目",
                    "type": "string"
                },
                "type": {
                    "description": "类型 1-选择 2-判断",
                    "type": "integer"
                }
            }
        },
        "form_req.ExercisesReq": {
            "type": "object",
            "required": [
                "answers",
                "content_id"
            ],
            "properties": {
                "answers": {
                    "description": "答案提交",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/form_req.ExercisesAnswer"
                    }
                },
                "content_id": {
                    "description": "内容id",
                    "type": "integer"
                }
            }
        },
        "form_req.LearningContentListReq": {
            "type": "object",
            "required": [
                "course_id"
            ],
            "properties": {
                "course_id": {
                    "description": "课程id",
                    "type": "integer"
                },
                "ordering_learned": {
                    "description": "根据已学习人数排序 learned/-learned",
                    "type": "string"
                },
                "ordering_un_learned": {
                    "description": "根据未学习人数排序 unlearned/-unlearned",
                    "type": "string"
                },
                "page": {
                    "description": "分页",
                    "type": "integer"
                },
                "page_size": {
                    "description": "分页大小",
                    "type": "integer"
                },
                "search": {
                    "description": "根据学习内容搜索",
                    "type": "string"
                }
            }
        },
        "form_req.LearningResultReq": {
            "type": "object",
            "required": [
                "content_id",
                "status"
            ],
            "properties": {
                "content_id": {
                    "description": "学习内容id",
                    "type": "integer"
                },
                "status": {
                    "description": "学习状态 learned-已学习/unlearned-未学习",
                    "type": "string"
                }
            }
        },
        "form_req.NoticeReq": {
            "type": "object",
            "properties": {
                "course_id": {
                    "description": "课程号",
                    "type": "integer"
                },
                "learning_content_id": {
                    "description": "学习内容id",
                    "type": "integer"
                },
                "user_id": {
                    "description": "学生学号",
                    "type": "string"
                }
            }
        },
        "form_req.RegisterReq": {
            "type": "object",
            "required": [
                "content_id"
            ],
            "properties": {
                "content_id": {
                    "description": "学习内容id",
                    "type": "integer"
                }
            }
        },
        "form_req.RegisterResultReq": {
            "type": "object",
            "required": [
                "content_id",
                "register_result"
            ],
            "properties": {
                "content_id": {
                    "description": "学习内容id",
                    "type": "integer"
                },
                "register_result": {
                    "description": "签到结果，unfinished-未签到/finished-已签到",
                    "type": "string"
                }
            }
        },
        "form_req.TalkInfoReq": {
            "type": "object",
            "properties": {
                "course_id": {
                    "description": "课程号",
                    "type": "integer"
                },
                "learning_content_id": {
                    "description": "学习内容id",
                    "type": "integer"
                },
                "talk_id": {
                    "description": "讨论id",
                    "type": "integer"
                }
            }
        },
        "form_req.TalkReq": {
            "type": "object",
            "properties": {
                "course_id": {
                    "description": "课程号",
                    "type": "integer"
                },
                "learning_content_id": {
                    "description": "学习内容id",
                    "type": "integer"
                },
                "talk_id": {
                    "description": "讨论id",
                    "type": "integer"
                }
            }
        },
        "form_req.UpdateCourseReq": {
            "type": "object",
            "required": [
                "course_id"
            ],
            "properties": {
                "class": {
                    "description": "班级",
                    "type": "integer"
                },
                "course_id": {
                    "description": "课程id",
                    "type": "integer"
                },
                "course_name": {
                    "description": "课程名称",
                    "type": "string"
                },
                "grade": {
                    "description": "年级",
                    "type": "integer"
                }
            }
        },
        "form_req.UserPasswordReq": {
            "type": "object",
            "required": [
                "confirm",
                "password",
                "role",
                "user_id",
                "user_name"
            ],
            "properties": {
                "confirm": {
                    "description": "确认用户密码",
                    "type": "string"
                },
                "password": {
                    "description": "新密码",
                    "type": "string"
                },
                "role": {
                    "description": "用户角色",
                    "type": "integer"
                },
                "user_id": {
                    "description": "学生学号/教师工号",
                    "type": "string"
                },
                "user_name": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "form_resp.AuthLoginResp": {
            "type": "object",
            "properties": {
                "authorization": {
                    "description": "用户Token信息",
                    "type": "string"
                },
                "role": {
                    "description": "用户权限",
                    "type": "integer"
                },
                "user_id": {
                    "description": "用户ID",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "form_resp.AuthVerifyCodeResp": {
            "type": "object",
            "properties": {
                "captid": {
                    "description": "验证码唯一ID",
                    "type": "string"
                },
                "image": {
                    "description": "验证码图片数据",
                    "type": "string"
                }
            }
        },
        "form_resp.CourseInfoItem": {
            "type": "object",
            "properties": {
                "course_id": {
                    "description": "课程ID",
                    "type": "integer"
                },
                "course_name": {
                    "description": "课程名称",
                    "type": "string"
                }
            }
        },
        "form_resp.CourseInfoResp": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/form_resp.CourseInfoItem"
                    }
                }
            }
        },
        "form_resp.CourseListItem": {
            "type": "object",
            "properties": {
                "class": {
                    "description": "班级",
                    "type": "integer"
                },
                "course_id": {
                    "description": "课程ID",
                    "type": "integer"
                },
                "course_name": {
                    "description": "课程名称",
                    "type": "string"
                },
                "create_tm": {
                    "description": "创建时间",
                    "type": "string"
                },
                "grade": {
                    "description": "年级",
                    "type": "integer"
                },
                "total_member": {
                    "description": "总人数",
                    "type": "integer"
                }
            }
        },
        "form_resp.CourseListResp": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/form_resp.CourseListItem"
                    }
                }
            }
        },
        "form_resp.ExerciseResult": {
            "type": "object",
            "properties": {
                "answer": {
                    "description": "正确答案",
                    "type": "string"
                },
                "correct": {
                    "description": "判断是否正确",
                    "type": "boolean"
                },
                "id": {
                    "description": "课后练习id",
                    "type": "integer"
                }
            }
        },
        "form_resp.ExercisesItem": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "课后练习id",
                    "type": "integer"
                },
                "options": {
                    "description": "选项",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "question": {
                    "description": "题目",
                    "type": "string"
                },
                "type": {
                    "description": "类型 0-选择 1-判断",
                    "type": "integer"
                }
            }
        },
        "form_resp.ExercisesResp": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/form_resp.ExerciseResult"
                    }
                }
            }
        },
        "form_resp.GetExercisesResp": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "习题数",
                    "type": "integer"
                },
                "results": {
                    "description": "练习题",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/form_resp.ExercisesItem"
                    }
                }
            }
        },
        "form_resp.LearningContentItem": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "学习内容",
                    "type": "string"
                },
                "content_id": {
                    "description": "学习内容id",
                    "type": "integer"
                },
                "learned": {
                    "description": "已学习",
                    "type": "integer"
                },
                "unlearned": {
                    "description": "未学习",
                    "type": "integer"
                }
            }
        },
        "form_resp.LearningContentListResp": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/form_resp.LearningContentItem"
                    }
                }
            }
        },
        "form_resp.LearningResultResp": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "人数",
                    "type": "integer"
                },
                "student_info": {
                    "description": "学生信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/form_resp.StudentItem"
                    }
                }
            }
        },
        "form_resp.NoticeItem": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "通知数量",
                    "type": "integer"
                },
                "type": {
                    "description": "通知类型 0-签到/1-课堂讨论/2-课后练习",
                    "type": "integer"
                }
            }
        },
        "form_resp.NoticeResp": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/form_resp.NoticeItem"
                    }
                }
            }
        },
        "form_resp.RegisterResultResp": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "人数",
                    "type": "integer"
                },
                "student_info": {
                    "description": "学生信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/form_resp.StudentItem"
                    }
                }
            }
        },
        "form_resp.StatusResp": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "基本状态(string)",
                    "type": "string"
                }
            }
        },
        "form_resp.StudentItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "form_resp.TalkInfoResp": {
            "type": "object",
            "properties": {
                "result": {
                    "description": "讨论结果",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/form_resp.UserItem"
                    }
                },
                "topic": {
                    "description": "讨论话题",
                    "type": "string"
                }
            }
        },
        "form_resp.UserInfoResp": {
            "type": "object",
            "properties": {
                "class": {
                    "description": "班级",
                    "type": "integer"
                },
                "grade": {
                    "description": "年级",
                    "type": "integer"
                },
                "last_login_time": {
                    "description": "最近登陆时间",
                    "type": "string"
                },
                "login_time": {
                    "description": "注册时间",
                    "type": "string"
                },
                "role": {
                    "description": "用户角色 1-老师、2-学生",
                    "type": "integer"
                },
                "user_id": {
                    "description": "学生学号/教师工号",
                    "type": "string"
                },
                "user_name": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "form_resp.UserItem": {
            "type": "object",
            "properties": {
                "talk_info": {
                    "description": "讨论信息",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户id",
                    "type": "string"
                },
                "user_name": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "form_resp.UserPasswordResp": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "用户密码",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
